### ISSUE TITLE
Umbrella Issue: find/replace overlay issues

### ISSUE THREAD

**Issue by Wittmaxi** [eclipse-platform/eclipse.platform.ui#2021]
This Issue documents my views on priority for the issues of the find/replace overlay.
High issues are issues which are blocking a possible release

### high
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2033
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2011
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2007
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2006
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/1994
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/1992
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/1989
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/1983
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/1991
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/1951
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/1945
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/1907
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2053
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2046
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2054
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2059
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2075
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2138
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2147
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2244
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2246
- [x] https://github.com/eclipse-platform/eclipse.platform.swt/issues/1447
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2285
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2322
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2161
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2509

### medium
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2018
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2012
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/1998
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/1997
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/1995
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/1993
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/1953
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/1915
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/1914
- [ ] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2055
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2066
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2080
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2092
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2099
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2139
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2158
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2162
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2270
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2291
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2478
- [ ] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2512
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/1911
- [ ] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2651
- [ ] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2955

### low
- [ ] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2034
- [ ] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2015
- [ ] https://github.com/eclipse-platform/eclipse.platform.ui/issues/1996
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/1944
- [ ] https://github.com/eclipse-platform/eclipse.platform.ui/issues/1912
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/1913
- [ ] https://github.com/eclipse-platform/eclipse.platform.ui/issues/1909
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2035
- [ ] https://github.com/eclipse-platform/eclipse.platform.ui/issues/1813
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2060
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2100
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2105
- [ ] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2145
- [ ] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2146
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2194
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2195
- [ ] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2473
- [ ] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2498
- [ ] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2520
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2666
- [ ] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2737
- [ ] https://github.com/eclipse-pde/eclipse.pde/issues/1749
- [ ] https://github.com/eclipse-platform/eclipse.platform.ui/issues/3144
- [ ] https://github.com/eclipse-platform/eclipse.platform.ui/issues/3865

### unclear
- [ ] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2284
- [ ] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2679

**Comment by Wittmaxi** [comment]
@HeikoKlare did I miss anything we discussed in our meeting?

**Comment by HeikoKlare** [comment]
Priorities look sound. Just the following issues were missing (I have added them to the initial post with the mentioned priorities):
- #1907 (high)
- #1914 (medium)
- #1998 (medium)

**Comment by arsenalzp** [comment]
Hello,
Any of those issues are for newcomers (good-first-issue)?

**Comment by Wittmaxi** [comment]
@arsenalzp Hi, if you are looking to get into them I can give you some pointers, just ask in the corresponding issues :)

These should be (relatively) straight-forward to do:
https://github.com/eclipse-platform/eclipse.platform.ui/issues/1991
https://github.com/eclipse-platform/eclipse.platform.ui/issues/2012

This one might is a bit harder, but maybe you can help me by creating a prototype for how such a resize-mechanism could look like?
https://github.com/eclipse-platform/eclipse.platform.ui/issues/1996

Some issues are already actively being fixed, others are more involved. I can of course help you get into them too, just ask 😀

Please add me to the reviewers of your PRs so that I can roughly see what is happening in the Overlay!

**Comment by arsenalzp** [comment]
> @arsenalzp Hi, if you are looking to get into them I can give you some pointers, just ask in the corresponding issues :)
> 
> These should be (relatively) straight-forward to do: #1991 #2012
> 
> This one might is a bit harder, but maybe you can help me by creating a prototype for how such a resize-mechanism could look like? #1996
> 
> Some issues are already actively being fixed, others are more involved. I can of course help you get into them too, just ask 😀
> 
> Please add me to the reviewers of your PRs so that I can roughly see what is happening in the Overlay!

Thank you for detail explanation!
Let me explore the project and its architecture a little bit :)

**Comment by HeikoKlare** [comment]
I have just added #2033 (high prio) and #2034 (low prio) to the list.

**Comment by lukeu** [comment]
Early adopter feedback - maybe consider adding #1813 to the list?

I almost logged an issue but realised the prior issue existed. I'd seen it occasionally with ALT+click to make multiple cursors (which I don't do often). I think the Find overlay will make this much easier to encounter, however.

Say I need to do a multple replace. Often I'll copy the "new" text to the clipboard, select the old text and then...
 * Maybe I'll even just use ["Find Again", "Paste"] keys a few times _(very fast, no find UI needed)_, or
 * If there's **more than a few** hits, I'll...
    * Press Ctrl+F _(the "old" text is entered into the Find Overlay - nice)_
    * Press Ctrl+Enter _(a multi-selection is made - nice)_
    * Whack ESC, Paste

The last step just seems more quick & natural to me than [expand the overlay, paste it there, replace, close it]

The problem is: if Find found 100 hits - this bug inserts 10,000 copies (!)

**Comment by Wittmaxi** [comment]
@lukeu I see, that is really really annyoing. To me, that is not in scope; I have too many things to do already, and your bug is not directly related to the overlay (which is priority #1). I would need to read into a completely new part of the code which I did not touch so far, so I won't add it into this umbrella-issue (which acts as a to-do list for @HeikoKlare and me)

**Comment by HeikoKlare** [comment]
Thank you for your early adopter feedback, @lukeu! It is great to see you testing new functionality and then also giving feedback on it. That's very valuable!

I agree that the reported bug is quite annoying. Personally, I did not use the described workflow so far but rely on the "replace all" functionality of the find/replace dialog/overlay, but I see how beneficial the workflow can be (and when you can use it, it should of course work as expected anyway).
Since it's not a bug introduced by the new UI, I also do not see an urgent need of having it fixed in the context of the find/replace overlay and would consider it with lower priority than other issues that might reduce acceptance and/or adoption of the new UI. Still, as you mentioned that the issue becomes more "obvious" with the new UI (https://github.com/eclipse-platform/eclipse.platform.ui/issues/1813#issuecomment-2211226306), I would propose to simply put it on this issue's list (even though it might be priority "low" in the context of this issue).

**Comment by Wittmaxi** [comment]
I am adding https://github.com/eclipse-platform/eclipse.platform.ui/issues/2053
with high priority

**Comment by HeikoKlare** [comment]
Also add #2046 (with high prio)?

**Comment by Wittmaxi** [comment]
@HeikoKlare Yes! Done!

**Comment by Wittmaxi** [comment]
Added https://github.com/eclipse-platform/eclipse.platform.ui/issues/2055 with medium priority
Added https://github.com/eclipse-platform/eclipse.platform.ui/issues/2054 with high priority

**Comment by Wittmaxi** [comment]
Added https://github.com/eclipse-platform/eclipse.platform.ui/issues/2059 with high priority
@HeikoKlare is this related to your recent changes to the positioning of the overlay?

**Comment by HeikoKlare** [comment]
Added:
* #2060 (prio low)
* #2075 (prio high)

**Comment by HeikoKlare** [comment]
Added with medium priority (feel free to change if you see a different prio fitting):
- #2080

**Comment by Wittmaxi** [comment]
Medium Prio: 
https://github.com/eclipse-platform/eclipse.platform.ui/issues/2099

Low Prio:
https://github.com/eclipse-platform/eclipse.platform.ui/issues/2100

**Comment by Wittmaxi** [comment]
Low prio: https://github.com/eclipse-platform/eclipse.platform.ui/issues/2105

**Comment by HeikoKlare** [comment]
Added three issues/proposals with prio "medium" based on a test session at SAP. Thank you for testing and reporting!
- #2158
- #2161
- #2162

**Comment by HeikoKlare** [comment]
Added with low priority:
- #2194
- #2195

**Comment by nettozahler** [comment]
Thank you for all the work on this find/replace overlay. Using it I have found something which looks like a bug to me. In NON-regex (standard) mode one can simply add a phrase in the search and replace fields and change one occurrence after the other by pressing ENTER repeatedly. But this does not work for me in regex mode. Here hitting ENTER has no effect and I must use the "arrow down" button to jump to the next occurrence each time. I have not found an existing bug report for this issue yet. If you confirm this being a bug I can open a new bug report. But maybe I am missing something?

**Comment by HeikoKlare** [comment]
Thank you for reporting the issue, @nettozahler! We were not aware of that bug yet (and I agree that it is a bug), so we do not have a GitHub issue for it yet. It would be great if you can open a [new issue for that](https://github.com/eclipse-platform/eclipse.platform.ui/issues/new?assignees=&labels=bug&projects=&template=report-a-bug.md&title=). It should be easy to fix and would be great to still have it in the upcoming release, so we will have a look as soon as possible.

**Comment by nettozahler** [comment]
Here is the fresh bug report: https://github.com/eclipse-platform/eclipse.platform.ui/issues/2203#issue-2469948186. I think I cannot add it to this "umbrella" myself?

**Comment by akurtakov** [comment]
There seems to be huge issue with this feature under Linux/wayland https://github.com/eclipse-platform/eclipse.platform.swt/issues/1447

**Comment by HeikoKlare** [comment]
> There seems to be huge issue with this feature under Linux/wayland [eclipse-platform/eclipse.platform.swt#1447](https://github.com/eclipse-platform/eclipse.platform.swt/issues/1447)

To me, it's actually not appears to be a bug of this feature but a bug of the `Shell` implementation when used on Wayland, see https://github.com/eclipse-platform/eclipse.platform.swt/issues/1447#issuecomment-2331720348

**Comment by akurtakov** [comment]
> > There seems to be huge issue with this feature under Linux/wayland [eclipse-platform/eclipse.platform.swt#1447](https://github.com/eclipse-platform/eclipse.platform.swt/issues/1447)
> 
> To me, it's actually not appears to be a bug of this feature but a bug of the `Shell` implementation when used on Wayland, see [eclipse-platform/eclipse.platform.swt#1447 (comment)](https://github.com/eclipse-platform/eclipse.platform.swt/issues/1447#issuecomment-2331720348)

That's exactly why I reported it to swt but still it's a major regression in the overall UX.

**Comment by HeikoKlare** [comment]
Yes, it's definitely a regression. At least, this is something that you can configure via preferences, so you are not stuck with the bad UX. But still it's a bad experience to see this as default behavior on a fresh installation. And, of course, you need to know (1) that you can configure it and (2) where you have to configure it, since the popup easing this process for you does not appear either. I do not see a way of automatically disabling the feature (for Wayland), except for code-based changes.

If I am not mistaken, the welcome page is also static, local content, isn't it? Otherwise, if that information was dynamically loaded from a remote URL and could thus be changed after deployment of the application, it could be a means to inform users about the issue (and the simple solution for it).

**Comment by HeikoKlare** [comment]
Added with high prio:
- https://github.com/eclipse-platform/eclipse.platform.ui/issues/2244
- https://github.com/eclipse-platform/eclipse.platform.ui/issues/2246
- https://github.com/eclipse-platform/eclipse.platform.swt/issues/1447

**Comment by HeikoKlare** [comment]
Added:
- https://github.com/eclipse-platform/eclipse.platform.ui/issues/2270
- https://github.com/eclipse-platform/eclipse.platform.ui/issues/2284
- https://github.com/eclipse-platform/eclipse.platform.ui/issues/2285
- https://github.com/eclipse-platform/eclipse.platform.ui/issues/2291

**Comment by deepika-u** [comment]
A query: Do we have an option to clear the history and have a fresh set of history i want to build/accumulate from now on?

**Comment by HeikoKlare** [comment]
> A query: Do we have an option to clear the history and have a fresh set of history i want to build/accumulate from now on?

If I am not mistaken, there is no such option yet. It might be possible to clear the dialog settings, in which the history is stored, manually, but not in a proper way via the UI. I don't see a necessity for it since old history entries will simply be removed upon addition of new entries (and the existing dialog also had not option for it), but if you find that a useful function, feel free to create an issue from it.

**Comment by stephan-herrmann** [comment]
To me #2473 feels like a significant regression.

**Comment by HeikoKlare** [comment]
> To me #2473 feels like a significant regression.

I have added #2473 to the list of issues, but my current assessment regarding "significance" of the issue is different. It only affects a very specific workflow, so that if you are used to that workflow, it is probably annoying, but I am unsure whether the workflow is widely used.

**Comment by tobiasmelcher** [comment]
https://github.com/eclipse-platform/eclipse.platform.ui/issues/2509 might be added to this list

**Comment by HeikoKlare** [comment]
> #2509 might be added to this list

Thank you for reporting this. I've added it to the list with medium priority.
I also ranked #2161 up to high priority, as I consider this the most important of the currently open issues, in particular higher than the other medium priority ones.

**Comment by HannesWell** [comment]
> > #2509 might be added to this list
> 
> Thank you for reporting this. I've added it to the list with medium priority.

Can you please reevaluate the priority? At least I personally find it very annoying when running into the described situation.

**Comment by HeikoKlare** [comment]
> Can you please reevaluate the priority? At least I personally find it very annoying when running into the described situation.

It's fine for me to increase the priority. In particular, since the priorities should be driven by demand of the community and initial priorities (assigned by an individual) may be driven by an the individual's assessment with incomplete assumptions about the usage of features. So feel free to simply adapt the priorities here. Just keep in mind that they should really reflect the according relevance, as people who want to take over issues and contribute fixes for them should be properly guided in selecting a reasonable issue by the list of priorities.

**Comment by mbooth101** [comment]
I just filed this: https://github.com/eclipse-platform/eclipse.platform.ui/issues/2646

**Comment by HannesWell** [comment]
Just added https://github.com/eclipse-pde/eclipse.pde/issues/1749 with low priority. Anyone interested in working on it, is invited to do so. If none takes care of it, I might also take a look at it in the future.
