### ISSUE TITLE
[Sticky Scrolling] Umbrella issue

### ISSUE THREAD

**Issue by Christopher-Hermann** [eclipse-platform/eclipse.platform.ui#2152]
This Issue documents all know issues in the sticky scrolling feature with priorties.

### High
- [x] [Sticky scrolling should allow to be fed by language-specific info/annotations](https://github.com/eclipse-platform/eclipse.platform.ui/issues/1950)
- [x] [[Sticky scrolling] Commented-out code is being incorrectly recognized](https://github.com/eclipse-platform/eclipse.platform.ui/issues/2128)
- [x] [Sticky scrolling resets on comment lines](https://github.com/eclipse-platform/eclipse.platform.ui/issues/2338)

### Low
- [ ] [StickyScrollControll Doesn't Show Whitespace Chars](https://github.com/eclipse-platform/eclipse.platform.ui/issues/1971)
- [x] [Vertical Scrolling not handled correctly in StickyScrollControl](https://github.com/eclipse-platform/eclipse.platform.ui/issues/1966)
- [x] ["Show line numbers" settings is not correctly handled](https://github.com/eclipse-platform/eclipse.platform.ui/issues/2269)

### To be checked
- [x] There are several issues in https://github.com/eclipse-platform/eclipse.platform.ui/issues/1954, need to check what issues are still open.
- [x] There are several issues in https://github.com/eclipse-platform/eclipse.platform.ui/pull/1894, need to check what issues are still open.

**Comment by twwwt** [comment]
Doesn't work so well when one uses a code format where opening braces of a block begin on a new line:
![workspace-os_-_polyde-cli_src_main_java_org_polyde_cli_Polyde_java_-_Eclipse_IDE.pdf](https://github.com/user-attachments/files/17049325/workspace-os_-_polyde-cli_src_main_java_org_polyde_cli_Polyde_java_-_Eclipse_IDE.pdf)
For such formats the previous line should also be sticky to provide sufficient context.

What is more, the horizontal indentation doesn't seem to align perfectly when using tabs for indentation.

**Comment by BeckerWdf** [comment]
I think this is the same issue as reported in https://github.com/eclipse-platform/eclipse.platform.ui/issues/1950.
Pls. reopen if you don't agree.

**Comment by BeckerWdf** [comment]
> Doesn't work so well when one uses a code format where opening braces of a block begin on a new line: ![workspace-os_-polyde-cli_src_main_java_org_polyde_cli_Polyde_java-_Eclipse_IDE.pdf](https://github.com/user-attachments/files/17049325/workspace-os_-_polyde-cli_src_main_java_org_polyde_cli_Polyde_java_-_Eclipse_IDE.pdf) For such formats the previous line should also be sticky to provide sufficient context.
> 
> What is more, the horizontal indentation doesn't seem to align perfectly when using tabs for indentation.

I think this is the same issue as reported in https://github.com/eclipse-platform/eclipse.platform.ui/issues/1950.
